### PR TITLE
Questionnaire update and security fixes

### PR DESCRIPTION
**Pull request by Phildesro123**
- Fixed questionnaire submit button (We would just need to implement the backend and Cooper's algorithm)
- Added state to questionnaire.js
- Made StarRating component use a prop
- Added dotenv
- Removed mongoDB uri from appearing in repo
In order to fix go forward on testing for mongoDB, create a .env file in the root folder and  paste `MONGODB_URI={your mongo uri here}` into it.

Questionnaire 
image

Result of submit button
image

### CODE REVIEW

**Review by avin1100 — COMMENTED** [review]
changed

**Review by yasaad — COMMENTED** [review]
Looks good!

**Review by yasaad — COMMENTED** [review]
Looks good!

**Review by yasaad — APPROVED** [review]
Looks good!

**Pull request merged**
